"""
Neural surrogate for instant energy-level prediction + inverse design.
Trained offline (see train_surrogate.py) on data generated by the validated
solver in qdot_physics.py. Same weights file used by the browser (JS) version —
both give identical predictions.
"""
import json
import os
import numpy as np
from qdot_physics import MATERIALS, SHAPES, HC

_WEIGHTS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "surrogate_weights.json")
with open(_WEIGHTS_PATH) as f:
    W = json.load(f)

_x_mean = np.array(W["x_mean"])
_x_scale = np.array(W["x_scale"])
_y_mean = np.array(W["y_mean"])
_y_scale = np.array(W["y_scale"])
_weights = [np.array(w) for w in W["weights"]]
_biases = [np.array(b) for b in W["biases"]]
METRICS = W["metrics"]


def _forward(raw):
    x = (np.array(raw) - _x_mean) / _x_scale
    for i, (Wl, bl) in enumerate(zip(_weights, _biases)):
        x = x @ Wl + bl
        if i < len(_weights) - 1:
            x = np.maximum(x, 0)
    return x * _y_scale + _y_mean


def predict(shape, size_nm, V0, material):
    mat = MATERIALS[material]
    onehot = [1.0 if s == shape else 0.0 for s in SHAPES]
    raw = onehot + [size_nm, V0, mat["Eg"], mat["me"], mat["mh"]]
    Ee0, Eh0 = _forward(raw)
    gap = mat["Eg"] + Ee0 + Eh0
    lam = HC / gap
    return {"Ee0": Ee0, "Eh0": Eh0, "gap": gap, "lambda_nm": lam}


def inverse_design(target_nm, shape, V0, material, lo=2.0, hi=14.0, iters=40):
    """Bisection search over size for a target absorption wavelength.
    Valid because lambda(size) is monotonically increasing (weaker confinement -> longer wavelength)."""
    def lam_at(sz):
        return predict(shape, sz, V0, material)["lambda_nm"]

    lam_lo, lam_hi = lam_at(lo), lam_at(hi)
    if target_nm <= lam_lo:
        return lo
    if target_nm >= lam_hi:
        return hi
    for _ in range(iters):
        mid = (lo + hi) / 2
        if lam_at(mid) < target_nm:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2
